version: "3.8"

volumes:
    db_volume:

services:
    db:
        image: postgres:11.7
        container_name: database_gateway
        environment:
            - POSTGRES_DB=database
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=postgres_password
        ports:
            - "5432:5432"
        volumes:
            - db_volume:/var/lib/postgresql/data

    tratamento:
        build: .
        entrypoint: ["python", "/src/main_tratamento.py"]
        depends_on:
          - db

    entrada:
        environment:
          INSERSAO_MANUAL: 'campo1;campo2;campo3;campo4'
        container_name: entrada
        build: .
        entrypoint: ["python", "/src/main_entrada.py"]
        depends_on:
          - db
        ports:
            - "7000:7000"
        expose:
            - "7000"

    cliente:
        environment:
          MENSAGEM_CLIENTE: 'm1;mensagem2;mensagem3;mensagem4'
        build: .
        entrypoint: ["python", "/src/entrada/cliente.py"]
        depends_on:
          - db
          - entrada

    testes:
        build: .
        entrypoint: ["/bin/bash", "-c", "pytest --cov --cov-report term-missing"]
        volumes:
            - ./src:/src