version: "3.8"

volumes:
    db_volume:

networks:
  private_network_library:
    name: network_database

services:
    db:
        image: postgres:11.7
        container_name: database_library
        environment:
            - POSTGRES_DB=database
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=postgres_password
        ports:
            - "5432:5432"
        networks:
            - private_network_library
        volumes:
            - db_volume:/var/lib/postgresql/data

    tratamento:
        build: .
        working_dir: /src/tratamento
        networks:
          - private_network_library
        depends_on:
          - db
