version: "3.8"

volumes:
    db_volume:

networks:
  private_network_gateway:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
    db:
        image: postgres:11.7
        container_name: database_gateway
        environment:
            - POSTGRES_DB=database
            - POSTGRES_USER=postgres_user
            - POSTGRES_PASSWORD=postgres_password
        ports:
            - "5432:5432"
        networks:
            private_network_gateway:
              ipv4_address: 10.5.0.3
        volumes:
            - db_volume:/var/lib/postgresql/data

    tratamento:
        build:
          context: .
          dockerfile: tratamento.Dockerfile
        networks:
            private_network_gateway:
              ipv4_address: 10.5.0.4
        depends_on:
          - db

    entrada:
        environment:
          INSERSAO_MANUAL: 'campo1;campo2;campo3;campo4'
        container_name: entrada
        build:
          context: .
          dockerfile: entrada.Dockerfile
        networks:
            private_network_gateway:
              ipv4_address: 10.5.0.5
        depends_on:
          - db
        ports:
            - "7000:7000"
        expose:
            - "7000"

    cliente:
        environment:
          MENSAGEM_CLIENTE: 'm1;mensagem2;mensagem3;mensagem4'
        build:
          context: .
          dockerfile: cliente.Dockerfile
        networks:
            private_network_gateway:
              ipv4_address: 10.5.0.6
        depends_on:
          - db
          - entrada
