SQL_CREATE_TABLE_STRING_RECEBIDA = """
CREATE TABLE IF NOT EXISTS STRING_RECEBIDA (
    id serial primary key,
    CAMPOS varchar(1024) 
);
"""

SQL_INSERT_STRING_RECEBIDA = f"""
INSERT INTO STRING_RECEBIDA
VALUES (DEFAULT, %s) 
RETURNING id;
"""

SQL_SELECT_ALL_STRING_RECEBIDA = """
SELECT * FROM STRING_RECEBIDA;
"""


SQL_CREATE_TABLE_TRATAMENTO_STRING_RECEBIDA = """
CREATE TABLE IF NOT EXISTS TRATAMENTO_STRING_RECEBIDA (
    id serial primary key,
    CAMPO1 varchar(256), 
    CAMPO2 varchar(256), 
    CAMPO3 varchar(256), 
    CAMPO4 varchar(256)
);
"""

SQL_INSERT_TRATAMENTO_STRING_RECEBIDA = f"""
INSERT INTO TRATAMENTO_STRING_RECEBIDA
VALUES (DEFAULT, %s, %s, %s, %s)
RETURNING id;
"""

SQL_SELECT_ALL_TRATAMENTO_STRING_RECEBIDA = """
SELECT * FROM TRATAMENTO_STRING_RECEBIDA;
"""

SQL_CREATE_TABLE_COMANDO_PENDENTE = """
CREATE TABLE IF NOT EXISTS COMANDO_PENDENTE (
    id serial primary key,
    CAMPOS varchar(1024),
    PROCESSADO BOOLEAN NOT NULL DEFAULT FALSE 
);
"""

SQL_INSERT_COMANDO_PENDENTE = f"""
INSERT INTO COMANDO_PENDENTE
VALUES (DEFAULT, %s, False)
RETURNING id;
"""

SQL_SELECT_ALL_COMANDO_PENDENTE = """
SELECT * FROM COMANDO_PENDENTE WHERE PROCESSADO IS False;
"""

SQL_SELECT_BY_ID_COMANDO_PENDENTE = """
SELECT * FROM COMANDO_PENDENTE WHERE ID = %s;
"""

SQL_UPDATE_COMANDO_PROCESSADO = """
UPDATE COMANDO_PENDENTE 
SET PROCESSADO = True
WHERE ID = %s;
"""